#!/bin/bash

shopt -s nullglob
set -e

_argtoyear() {
	if [[ "${#1}" == "2" ]]; then
		echo "20$1"
	elif [[ "${#1}" == "1" ]]; then
		echo "202$1"
	else
		echo "$1"
	fi
}
_argtoday() {
	if [[ "${#1}" == "1" ]]; then
		echo "0$1"
	else
		echo "$1"
	fi
}

if [[ "$1" == "build" ]]; then
	"$0" new "$2" "$3" "$4"
	"$0" clean "$2" "$3"
	cd "$(dirname "$0")"/"$(_argtoyear "$2")"/"$(_argtoday "$3")"
	if [ ! -f .lang ]; then
		echo "$(tput bold)no .lang found$(tput sgr0)" 1>&2
		exit 1
	fi
	if [ -z "$(cat .lang | xargs)" ]; then
		echo "$(tput bold).lang is empty$(tput sgr0)" 1>&2
		exit 1
	fi
	case "$(cat .lang)" in
		c++*|gnu++*)
			rm -f _tc.json
			for file in *.cpp; do
				echo "$(tput bold)building ${file%.*}:$(tput sgr0)" 1>&2
				echo "g++ $file -o out/${file%.*} -Wall -Wextra -Wpedantic -std=$(cat .lang)" 1>&2
				if [ ! -f compile_commands.json ]; then
					bear --append --output _tc.json -- g++ "$file" -o out/"${file%.*}" -Wall -Wextra -Wpedantic "-std=$(cat .lang)" 1>&2
				else
					g++ "$file" -o out/"${file%.*}" -Wall -Wextra -Wpedantic "-std=$(cat .lang)" 1>&2
				fi
			done
			if [ -f _tc.json ]; then
				mv _tc.json compile_commands.json
			fi
		;;
		c*|gnu*|iso9899*)
			rm -f _tc.json
			for file in *.c; do
				echo "$(tput bold)building ${file%.*}:$(tput sgr0)" 1>&2
				echo "gcc $file -o ${file%.*} -Wall -Wextra -Wpedantic -std=$(cat .lang) -lc" 1>&2
				if [ ! -f compile_commands.json ]; then
					bear --append --output _tc.json -- gcc "$file" -o out/"${file%.*}" -Wall -Wextra -Wpedantic "-std=$(cat .lang)" 1>&2
				else
					gcc "$file" -o out/"${file%.*}" -Wall -Wextra -Wpedantic "-std=$(cat .lang)" 1>&2
				fi
				if [ -f _tc.json ]; then
					mv _tc.json compile_commands.json
				fi
			done
		;;
		asm-x86-64|assembly-x86-64|asm-x64|assembly-x64)
			for file in *.asm; do
				echo "$(tput bold)building ${file%.*}:$(tput sgr0)" 1>&2
				echo "as $file -o out/${file%.*}.o && ld -s -o ${file%.*} ${file%.*}.o" 1>&2
				as $file -o ${file%.*}.o 1>&2 && ld -s -o out/${file%.*} ${file%.*}.o 1>&2
				rm ${file%.*}.o
			done
		;;
		hs|haskell)
			for file in *.hs; do
				echo "$(tput bold)building ${file%.*}:$(tput sgr0)" 1>&2
				echo "ghc $file -o out/${file%.*}" 1>&2
				ghc $file -o out/${file%.*} 1>&2
				rm ${file%.*}.o ${file%.*}.hi
			done
		;;
		erl|erlang)
			for file in *.erl; do
				echo "$(tput bold)building ${file%.*}:$(tput sgr0)" 1>&2
				echo "erlc $file -Wall -Werror -o out" 1>&2
				erlc $file -Wall -Werror -o out
			done
		;;
	esac
elif [[ "$1" == "run" ]]; then
	. "$0" build "$2" "$3"
	if [ -z "$(echo inputs/*)" ]; then
		echo "$(tput bold)no inputs found!$(tput sgr0)"
		exit 1
	fi
	if [ ! -f .lang ] || [ -z "$(cat .lang)" ]; then
		exit 1
	fi
	if [ -f inputs/"$4" ]; then
		for file in *.cpp *.c *.odin *.hs; do
			echo "$(tput bold)running ${file%.*} with input file $4:$(tput sgr0)" 1>&2
			cat inputs/"$4" | ./out/"${file%.*}"
		done
	else
		for input in inputs/*; do
			for file in *.cpp *.c *.odin *.hs; do
				echo "$(tput bold)running ${file%.*} with input file $input:$(tput sgr0)" 1>&2
				cat "$input" | ./out/"${file%.*}"
			done
		done
	fi
elif [[ "$1" == "clean" ]]; then
	rm -f "$(dirname "$0")"/"$(_argtoyear "$2")"/"$(_argtoday "$3")"/out/*
elif [[ "$1" == "new" ]] || [[ "$1" == "lang" ]]; then
	mkdir -p "$(dirname "$0")"/"$(_argtoyear "$2")"/"$(_argtoday "$3")"
	cd "$(dirname "$0")"/"$(_argtoyear "$2")"/"$(_argtoday "$3")"
	mkdir -p out
	mkdir -p inputs
	if [ -n "$(echo $4 | xargs)" ]; then
		printf "$4" > .lang
	fi
else
	echo "$(tput bold)$1: command not found!$(tput sgr0)" 1>&2
	exit 1
fi
